    version: '3.5'
    services:
      broadlinkac2mqtt:
        image: "https://github.com/REMOVED_USER/broadlinkac2mqtt_for_docker.git"
        container_name: "broadlinkac2mqtt_Simon"
        restart: "on-failure"
        volumes:
            - /var/lib/docker/volumes/broadlink_config/_data:/config