service:
  update_interval: 10 #Seconds
  log_level: error

Broker: "tcp://192.168.1.107:1883"

mqtt:
  ## Use mqtts for SSL support
  user: g4ssam
  password: Lozovaya95
  client_id: aircac2
  topic_prefix: aircon2
  auto_discovery_topic: homeassistant
  auto_discovery_topic_retain: false
  ## CA certificate in CRT format.
  # certificate_authority: "./config/cert/ca.crt"
  ## Don’t verify if the common name in the server certificate matches the value of broker
  # skip_cert_cn_check: true
  ## Authorization using client certificates
  # certificate_client: "./config/cert/client.crt"
  # key-client: "./config/cert/client.key"

devices:
  - ip: 192.168.1.63
    mac: 34ea34a6724e
    name: AC in Kitchen
    port: 80
    # Temperature Unit defines the temperature unit of the device, C or F.
    # If this is not set, the temperature unit is Celsius.
    temperature_unit: C
    temp_step: 1.0